### ISSUE TITLE
BUG REPORT

### ISSUE THREAD

**Issue by cleancoindev** [paraswap/demo-dapp#1]
My investor was working with me and we found out about pBTC.

I tried to use your platform to translate it into a different currency.  Had i done the transfer of 1 BTC, i would have lost all my value into your contract.

I want the payout from the 1000 ETH transaction insurance as a bug bounty.  Your protocol cost me reputation and harmed the DeFi reputation as a whole by what has happened.  We cannot do this or we will cause reputation issues with the financial industry and FinTech as a whole.

I am deeply embarrassed for you as well as because I lost nearly 2 hours in delayed bitcoin transactions and he has a bad first impression of DeFi now because of ParaSwap.

Please agree to pay out of the 1000 ETH insurance.  Otherwise I can go ahead and test it, and proceed with the transaction so you are forced to refund the 5k in lost value as well as the 1000 ETH.

** update:  later the investor said they were too scared to do it and decided to just demand the funds back into BTC and we were unable to finish our work due to all the delays and he quit for the day upset at DeFi's first impression. :(

**Comment by cleancoindev** [comment]
At the very least pay out 1 BTC of potential loss since you probably only cover the amount lost and whatever bounty bug fee you will pay for Severe Critical Errors.

You need to shut down the platform immediately for pBTC and fix this.  This can cause massive issues and makes us all look bad.

**Comment by cleancoindev** [comment]
Another bug in the SDK apparently too:

![Screenshot - 3_13_2020 , 9_18_33 PM](https://user-images.githubusercontent.com/31389482/76677254-42391080-6570-11ea-867e-e199689c564c.png)

**Comment by cleancoindev** [comment]
I am not assigning any blame between pBTC or Paraswap.  its probably the oracle or pBTC contracts?  not sure.  Let us know!

**Comment by mounibec** [comment]
Hello, ParaSwap is a DEX aggregator, which means it will display and try to improve the existing market price. We're not responsible for prices, as they come from external sources such as Uniswap, Bancor, Kyber..

We also don't have any feature to convert BTC <> pBTC, it's possible using this UI https://dapp.ptokens.io/pbtc-on-eth/issue-redeem which doesn't belong to us.

Nexus Mutual covers loss of funds due to bugs but this is not a bug since we display the exact market price and our exchange contract returns expected amount.
